# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 18b7dc6e9526000822a526a437aff9b869b69f74d759beb6fd655f3585a9fdd567c4a56533ae324446bbc9e2428d999f0287467a3c6a14f2b77bd260721aa0d4

test:
  secret_key_base: 2c58e8d46f30feb3783da6f5d804f571fe6d9d513ee7cadb5d8b129e9285b90ec3146a9dafa80e14b4e5e5109f9aee4fa17bd099bb7cd6df8419f17c15f63155

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
